Coding/java-core/pom.xml
ShortQuestions/hw1.md
ShortQuestions/placeholder.txt

Zhengyi cao/hw1

---

ShortQuestions/hw1_short_answers.md

Merge hw1 to yuche_lin_master branch

Yuche lin/hw1

---

MavenProject/.gitignore
MavenProject/pom.xml
MavenProject/src/main/java/com/chuwa/learn/Main.java
ShortQuestions/hw1.md
ShortQuestions/placeholder.txt

./MavenProject
./ShortQuestions/hw1.md
./ShortQuestions/placeholder.txt

xiaoyang hw1 submission

---

Coding/placeholder.txt
ShortQuestions/hw2_q1.java
ShortQuestions/hw2_short_answers.md
ShortQuestions/hw3_short_answers.md
codingQuestions/Coding1/Inh.java
codingQuestions/Coding1/Main.java
codingQuestions/Coding1/Poly.java
codingQuestions/Coding1/Student.java

Yuche lin/hw3

---

ShortQuestions/hw2_q1.java
ShortQuestions/hw2_short_answers.md
codingQuestions/Coding1/Inh.java
codingQuestions/Coding1/Main.java
codingQuestions/Coding1/Poly.java
codingQuestions/Coding1/Student.java

Add coding part of hw2 and short answers

Yuche lin/hw2

---

Coding/CollectionsExamples.java
ShortQuestions/hw3.md

the third homework

---

Coding/coding1/Main.java
MavenProject/hw1/pom.xml
README.md
ShortQuestions/README.md
ShortQuestions/hw1.md
ShortQuestions/hw2.md

Difan xue/hw2

---

MavenProject/hw1/pom.xml
README.md
ShortQuestions/README.md
ShortQuestions/hw1.md

Difan xue/hw1

---

Coding/coding1/.gitignore
Coding/coding1/pom.xml
Coding/coding1/src/main/java/com/chuwa/shawnlearning/Main.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/ParkingLot.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/ParkingSlot.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/evnt/SlotEvent.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/evnt/SlotEventEmitter.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/evnt/SlotEventEmitterBase.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/evnt/SlotEventListener.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/FirstAvailablePickPolicy.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/LeavingSlotEvent.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/ParkingLotManagement.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/ParkingSlotEvent.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/ParkingSlotManagement.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/ParkingSlotSM.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/ParkingSlotStatus.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/impl/SizeFitFitPolicy.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/policy/ParkingFitPolicy.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/policy/PickPolicy.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/policy/PolicyContext.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/stateful/SlotSM.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/stateful/SlotStateGraph.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/parking/stateful/SlotStatus.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/vehicle/Vehicle.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/vehicle/VehicleType.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/vehicle/impl/BigTruck.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/vehicle/impl/SmallCar.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/vehicle/impl/VehicleBase.java
Coding/coding1/src/main/java/com/chuwa/shawnlearning/vehicle/impl/VehicleFactory.java
ShortQuestions/hw2.md

Shawn zhang/hw2

---

Repo/MavenProject/java-core/pom.xml
Repo/MavenProject/java-core/src/main/java/com/chuwa/learn/Main.java
ShortQuestions/hw1.md

Xiao lian/hw1

---

ShortQuestions/hw1.md

Had some trouble about pushing a new branch into github repo, but finally finished it.

Homework 1(Git&Maven)

---

Coding/coding1/ParkingLot.java
Coding/placeholder.txt
ShortQuestions/hw2.md
ShortQuestions/placeholder.txt

first submission of hw2

---

Coding/CreditCardNotificationApp/.gitignore
Coding/CreditCardNotificationApp/pom.xml
Coding/CreditCardNotificationApp/src/main/java/com/hw3/CreditCardNotificationApp.java
Coding/CreditCardNotificationApp/src/main/java/com/hw3/EmailNotification.java
Coding/CreditCardNotificationApp/src/main/java/com/hw3/Notification.java
Coding/CreditCardNotificationApp/src/main/java/com/hw3/NotificationService.java
Coding/CreditCardNotificationApp/src/main/java/com/hw3/SMSNotification.java
Coding/CreditCardNotificationApp/src/main/java/com/hw3/User.java
Coding/CreditCardNotificationApp/src/main/java/com/hw3/WhatsAppNotification.java
Coding/collection/AdditionalMapExerciseTest.java
Coding/collection/ArrayListExerciseTest.java
Coding/collection/ArraysExerciseTest.java
Coding/collection/CollectionsExerciseTest.java
Coding/collection/CopyOnWriteArrayListExerciseTest.java
Coding/collection/HashMapExerciseTest.java
Coding/collection/HashSetExerciseTest.java
Coding/collection/LinkedHashMapExerciseTest.java
Coding/collection/LinkedListExerciseTest.java
Coding/collection/README.md
Coding/collection/TreeMapExerciseTest.java
Coding/collection/TreeSetExerciseTest.java
ShortQuestions/hw3.md

this is my hw3 answers

---

Coding/coding1/parking lot.java
ShortQuestions/hw2.md

Xiao lian/hw2

---

Coding/Main.java
Coding/placeholder.txt
MavenProject/.gitignore
MavenProject/pom.xml
MavenProject/src/main/java/com/chuwa/learn/Main.java
ShortQuestions/hw1.md
ShortQuestions/placeholder.txt

Initially, I have no clue how to do hw1 on homework 1 branch. So I did **hw1** on changqingdong_master. Now I create a Changqing_Dong/hw1 branch with hw1 and push it to **changqingdong_master**. Sorry for the inconvenience.

transferring hw1

---

Coding/coding1/ParkingSpot.java
Coding/coding1/Vehicle.java
Coding/coding1/VehicleSize.java
ShortQuestions/hw2.md

Changqing dong/hw2

---

Coding/02-java-core/src/main/java/com/chuwa/tutorial/t06_java8/exercise/ShoppingCartUtil.java
Coding/hw5/OddEvenPrinterA.java
Coding/hw5/OddEvenPrinterB.java
Coding/hw5/ThreeThreadPrinter.java
ShortQuestions/annotations.md
ShortQuestions/hw4.md
ShortQuestions/hw5.md
ShortQuestions/hw6.md
ShortQuestions/hw7.md

hw7 finish

---

Coding/GenericTest.java
Coding/Singleton/EagerSingleton.java
Coding/Singleton/LazySingleton.java
Coding/java8feature/.gitignore
Coding/java8feature/pom.xml
Coding/java8feature/src/main/java/Exercise/ShoppingCartTest.java
Coding/java8feature/src/main/java/default_interface_method/DIMImpl.java
Coding/java8feature/src/main/java/lambda/LambdaTest.java
Coding/java8feature/src/main/java/method_reference/MRTest.java
Coding/java8feature/src/main/java/optional/OptionalDemo.java
Coding/java8feature/src/main/java/optional/OptionalTest.java
Coding/java8feature/src/main/java/stream_api/Employee.java
Coding/java8feature/src/main/java/stream_api/EmployeeData.java
Coding/java8feature/src/main/java/stream_api/Product.java
Coding/java8feature/src/main/java/stream_api/ProductClient.java
Coding/java8feature/src/main/java/stream_api/StreamApiCreationTest.java
Coding/java8feature/src/main/java/stream_api/StreamApiEndOperation.java
Coding/java8feature/src/main/java/stream_api/StreamApiIntermediateOperation.java
Coding/java8feature/src/main/java/stream_api/StreamExercise.java
ShortQuestions/hw4.md

Jiaxiang gu/hw4

---

Coding/placeholder.txt

remove placeholder

---

Coding/21/OddEventPrinter.java
Coding/21/WaitNotify .java
Coding/23/PrintOddEven_ ReentrantLock and await.java
Coding/23/PrintOddEven_ synchronized and wait notify.java
Coding/24/PrintNumber.java
Coding/placeholder.txt
ShortQuestions/hw5.md
ShortQuestions/placeholder.txt

Changqing dong/hw5

---

Coding/hw5/CompletableFuture.java
Coding/hw5/OnlineStore.java
Coding/hw5/OnlineStore2.java
ShortQuestions/hw5.md

Xiao lian/hw5

---

Coding/hw4/generic/GenericClass.java
Coding/hw4/generic/GenericClassTest.java
Coding/hw4/generic/GenericMethod.java
Coding/hw4/generic/GenericMultiArguments.java
Coding/hw4/generic/NonGeneric.java
Coding/hw4/singleton.java
Coding/hw4/t06_java8/Java8.md
Coding/hw4/t06_java8/exercise/Customer.java
Coding/hw4/t06_java8/exercise/EmptyCartException.java
Coding/hw4/t06_java8/exercise/Item.java
Coding/hw4/t06_java8/exercise/ShoppingCart.java
Coding/hw4/t06_java8/exercise/ShoppingCartAnswer.java
Coding/hw4/t06_java8/exercise/ShoppingCartUtil.java
Coding/hw4/t06_java8/features/default_interface_method/Client.java
Coding/hw4/t06_java8/features/default_interface_method/DIMImpl.java
Coding/hw4/t06_java8/features/default_interface_method/DIML.java
Coding/hw4/t06_java8/features/lambda/Foo.java
Coding/hw4/t06_java8/features/lambda/LambdaLearn.java
Coding/hw4/t06_java8/features/method_reference/MethodReferenceExample.java
Coding/hw4/t06_java8/features/optional/OptionalDemo.java
Coding/hw4/t06_java8/features/optional/OptionalMainMethodTest.java
Coding/hw4/t06_java8/features/optional/OptionalTest.java
Coding/hw4/t06_java8/features/stream_api/Product.java
Coding/hw4/t06_java8/features/stream_api/ProductClient.java
Coding/hw4/t06_java8/features/stream_api/StreamApiCreationTest.java
Coding/hw4/t06_java8/features/stream_api/StreamApiEndOperation.java
Coding/hw4/t06_java8/features/stream_api/StreamApiIntermediateOperation.java
Coding/hw4/t06_java8/features/stream_api/StreamExercise.java
ShortQuestions/hw4.md

Xiao lian/hw4

---

ShortQuestions/hw9.md

Xiao lian/hw9

---

ShortQuestions/hw6.md

Xiao lian/hw6
